name: CI/CD

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: packages
        run: yarn install

      - name: Build source
        working-directory: packages
        run: yarn build

      - name: Test
        working-directory: packages
        run: yarn test

      - name: Build types
        working-directory: packages
        run: yarn build:dts

      - name: Build jsdocs
        working-directory: packages
        run: yarn build:jsdocs
