import { Geist, Geist_Mono } from 'next/font/google'
import ARMConfigProvider from '@/components/providers/arm-config-provider'

// Use dynamic import if you are encountering issues with SSR
// import dynamic from 'next/dynamic'
//
// const ARMConfigProvider = dynamic(
//   () => import('@/components/providers/arm-config-provider'),
//   { ssr: false }
// )

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap your application with arm-config-provider component */}
        <ARMConfigProvider>{children}</ARMConfigProvider>
      </body>
    </html>
  )
}
